openapi: 3.0.3
info:
  title: Admin Services API
  description: CRUD operations for service management
  version: 1.0.0

servers:
  - url: /api/admin

paths:
  /services:
    get:
      summary: List all services grouped by category
      operationId: listServices
      tags: [Services]
      security:
        - sessionAuth: []
      responses:
        '200':
          description: Services listed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServicesListResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      summary: Create a new service
      operationId: createService
      tags: [Services]
      security:
        - sessionAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceInput'
      responses:
        '201':
          description: Service created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '409':
          description: Slug already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /services/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid

    get:
      summary: Get a single service
      operationId: getService
      tags: [Services]
      security:
        - sessionAuth: []
      responses:
        '200':
          description: Service retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      summary: Update an existing service
      operationId: updateService
      tags: [Services]
      security:
        - sessionAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceInput'
      responses:
        '200':
          description: Service updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          description: Slug already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: Delete a service
      operationId: deleteService
      tags: [Services]
      security:
        - sessionAuth: []
      responses:
        '200':
          description: Service deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /services/{id}/order:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid

    patch:
      summary: Update service display order
      operationId: updateServiceOrder
      tags: [Services]
      security:
        - sessionAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [direction]
              properties:
                direction:
                  type: string
                  enum: [up, down]
      responses:
        '200':
          description: Order updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Cannot move (already at boundary)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  securitySchemes:
    sessionAuth:
      type: apiKey
      in: cookie
      name: hometown-session

  schemas:
    ServiceInput:
      type: object
      required: [name, description, isSubcontracted, categoryId]
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        slug:
          type: string
          maxLength: 100
          description: Optional - auto-generated from name if not provided
        description:
          type: string
          minLength: 10
          maxLength: 2000
        imageUrl:
          type: string
          format: uri
          maxLength: 500
        isSubcontracted:
          type: boolean
        categoryId:
          type: string
          format: uuid
        displayOrder:
          type: integer
          minimum: 0

    Service:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        slug:
          type: string
        description:
          type: string
        imageUrl:
          type: string
          nullable: true
        isSubcontracted:
          type: boolean
        categoryId:
          type: string
          format: uuid
        displayOrder:
          type: integer
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        _count:
          type: object
          properties:
            inquiries:
              type: integer

    ServiceWithCategory:
      allOf:
        - $ref: '#/components/schemas/Service'
        - type: object
          properties:
            category:
              $ref: '#/components/schemas/Category'

    Category:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        slug:
          type: string
        description:
          type: string
          nullable: true
        displayOrder:
          type: integer

    CategoryWithServices:
      allOf:
        - $ref: '#/components/schemas/Category'
        - type: object
          properties:
            services:
              type: array
              items:
                $ref: '#/components/schemas/Service'

    ServicesListResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: array
          items:
            $ref: '#/components/schemas/CategoryWithServices'

    ServiceResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          $ref: '#/components/schemas/ServiceWithCategory'

    DeleteResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            hasInquiries:
              type: boolean
            inquiryCount:
              type: integer

    SuccessResponse:
      type: object
      properties:
        success:
          type: boolean

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          enum: [false]
        error:
          type: string

  responses:
    Unauthorized:
      description: Not authenticated
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    ValidationError:
      description: Validation failed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
